name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy_staging:
    name: Deploying to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd bookmyshow-deployment
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart all
